default: &default
     adapter: <%= ENV.fetch("DATABASE_ADAPTER") { 'postgresql' } %>
     encoding: unicode
     host: <%= ENV.fetch('DATABASE_HOSTNAME') { 'localhost' }%>
     username: <%= ENV.fetch('DATABASE_USERNAME') { 'renthouse' }%>
     password: <%= ENV.fetch('DATABASE_PASSWORD') { 'rh@123' }%>
     pool: <%= ENV.fetch("DATABASE_POOL") { 5 } %>
development:
     <<: *default
     database: <%= ENV.fetch('DATABASE_NAME') { 'renthouse_development' }%>
